runtime: go111
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
skip_files:
- .*node_modules
- .*dist