steps:
- name: node:10-alpine
  entrypoint: yarn
  args: ['install']
  id: '01-yarn-install'
- name: node:10-alpine
  entrypoint: yarn
  args: ['build']
  id: '02-yarn-build'
  waitFor:
  - '01-yarn-install'
- name: golang:1.12
  env: ['GOPATH=/go']
  args: ['go', 'build']
  id: '03-go-build'
  waitFor:
  - '02-yarn-build'
- name: 'gcr.io/cloud-builders/gcloud'
  env: ['GOPATH=/go']
  args: ['app', 'deploy']
  id: '04-gcloud-app-deploy'
  waitFor:
  - '03-go-build'
timeout: '600s'
