steps:
- name: golang
  env: ['GOPATH=$PWD', 'GO111MODULE=on']
  args: ['go', 'build', './...']
- name: 'gcr.io/cloud-builders/gcloud'
  env: ['GOPATH=$PWD']
  args: ['app', 'deploy']
timeout: '600s'
